#############################################################################
# Makefile for building: debugger
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sat Mar 26 20:40:52 2016
# Project:  hw5.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile hw5.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = AddStatement.cpp \
		DebuggerWindow.cpp \
		DivStatement.cpp \
		EndStatement.cpp \
		Facile.cpp \
		GoSubStatement.cpp \
		GotoStatement.cpp \
		IfStatement.cpp \
		LetStatement.cpp \
		llistint.cpp \
		LoadWindow.cpp \
		main.cpp \
		mergetest.cpp \
		MultStatement.cpp \
		PrintAll.cpp \
		PrintStatement.cpp \
		ProgramState.cpp \
		ReturnStatement.cpp \
		stackint.cpp \
		SubStatement.cpp moc_DebuggerWindow.cpp \
		moc_LoadWindow.cpp
OBJECTS       = AddStatement.o \
		DebuggerWindow.o \
		DivStatement.o \
		EndStatement.o \
		Facile.o \
		GoSubStatement.o \
		GotoStatement.o \
		IfStatement.o \
		LetStatement.o \
		llistint.o \
		LoadWindow.o \
		main.o \
		mergetest.o \
		MultStatement.o \
		PrintAll.o \
		PrintStatement.o \
		ProgramState.o \
		ReturnStatement.o \
		stackint.o \
		SubStatement.o \
		moc_DebuggerWindow.o \
		moc_LoadWindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		hw5.pro
QMAKE_TARGET  = debugger
DESTDIR       = 
TARGET        = debugger

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: hw5.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile hw5.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile hw5.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/debugger1.0.0 || $(MKDIR) .tmp/debugger1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/debugger1.0.0/ && $(COPY_FILE) --parents AddStatement.h DebuggerWindow.h DivStatement.h EndStatement.h Facile.h GoSubStatement.h GotoStatement.h IfStatement.h LetStatement.h llistint.h LoadWindow.h msort.h MultStatement.h PrintAll.h PrintStatement.h ProgramState.h ReturnStatement.h stackint.h Statement.h SubStatement.h .tmp/debugger1.0.0/ && $(COPY_FILE) --parents AddStatement.cpp DebuggerWindow.cpp DivStatement.cpp EndStatement.cpp Facile.cpp GoSubStatement.cpp GotoStatement.cpp IfStatement.cpp LetStatement.cpp llistint.cpp LoadWindow.cpp main.cpp mergetest.cpp MultStatement.cpp PrintAll.cpp PrintStatement.cpp ProgramState.cpp ReturnStatement.cpp stackint.cpp SubStatement.cpp .tmp/debugger1.0.0/ && (cd `dirname .tmp/debugger1.0.0` && $(TAR) debugger1.0.0.tar debugger1.0.0 && $(COMPRESS) debugger1.0.0.tar) && $(MOVE) `dirname .tmp/debugger1.0.0`/debugger1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/debugger1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_DebuggerWindow.cpp moc_LoadWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_DebuggerWindow.cpp moc_LoadWindow.cpp
moc_DebuggerWindow.cpp: Facile.h \
		Statement.h \
		ProgramState.h \
		stackint.h \
		llistint.h \
		msort.h \
		DebuggerWindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) DebuggerWindow.h -o moc_DebuggerWindow.cpp

moc_LoadWindow.cpp: DebuggerWindow.h \
		Facile.h \
		Statement.h \
		ProgramState.h \
		stackint.h \
		llistint.h \
		msort.h \
		LoadWindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) LoadWindow.h -o moc_LoadWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

AddStatement.o: AddStatement.cpp AddStatement.h \
		ProgramState.h \
		stackint.h \
		llistint.h \
		Statement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AddStatement.o AddStatement.cpp

DebuggerWindow.o: DebuggerWindow.cpp DebuggerWindow.h \
		Facile.h \
		Statement.h \
		ProgramState.h \
		stackint.h \
		llistint.h \
		msort.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DebuggerWindow.o DebuggerWindow.cpp

DivStatement.o: DivStatement.cpp DivStatement.h \
		ProgramState.h \
		stackint.h \
		llistint.h \
		Statement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DivStatement.o DivStatement.cpp

EndStatement.o: EndStatement.cpp EndStatement.h \
		ProgramState.h \
		stackint.h \
		llistint.h \
		Statement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EndStatement.o EndStatement.cpp

Facile.o: Facile.cpp Statement.h \
		ProgramState.h \
		stackint.h \
		llistint.h \
		LetStatement.h \
		PrintStatement.h \
		PrintAll.h \
		EndStatement.h \
		GotoStatement.h \
		AddStatement.h \
		SubStatement.h \
		MultStatement.h \
		DivStatement.h \
		GoSubStatement.h \
		ReturnStatement.h \
		IfStatement.h \
		Facile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Facile.o Facile.cpp

GoSubStatement.o: GoSubStatement.cpp GoSubStatement.h \
		ProgramState.h \
		stackint.h \
		llistint.h \
		Statement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GoSubStatement.o GoSubStatement.cpp

GotoStatement.o: GotoStatement.cpp GotoStatement.h \
		ProgramState.h \
		stackint.h \
		llistint.h \
		Statement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GotoStatement.o GotoStatement.cpp

IfStatement.o: IfStatement.cpp IfStatement.h \
		ProgramState.h \
		stackint.h \
		llistint.h \
		Statement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IfStatement.o IfStatement.cpp

LetStatement.o: LetStatement.cpp LetStatement.h \
		Statement.h \
		ProgramState.h \
		stackint.h \
		llistint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LetStatement.o LetStatement.cpp

llistint.o: llistint.cpp llistint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o llistint.o llistint.cpp

LoadWindow.o: LoadWindow.cpp LoadWindow.h \
		DebuggerWindow.h \
		Facile.h \
		Statement.h \
		ProgramState.h \
		stackint.h \
		llistint.h \
		msort.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoadWindow.o LoadWindow.cpp

main.o: main.cpp LoadWindow.h \
		DebuggerWindow.h \
		Facile.h \
		Statement.h \
		ProgramState.h \
		stackint.h \
		llistint.h \
		msort.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mergetest.o: mergetest.cpp msort.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mergetest.o mergetest.cpp

MultStatement.o: MultStatement.cpp MultStatement.h \
		ProgramState.h \
		stackint.h \
		llistint.h \
		Statement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MultStatement.o MultStatement.cpp

PrintAll.o: PrintAll.cpp PrintAll.h \
		Statement.h \
		ProgramState.h \
		stackint.h \
		llistint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PrintAll.o PrintAll.cpp

PrintStatement.o: PrintStatement.cpp PrintStatement.h \
		Statement.h \
		ProgramState.h \
		stackint.h \
		llistint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PrintStatement.o PrintStatement.cpp

ProgramState.o: ProgramState.cpp ProgramState.h \
		stackint.h \
		llistint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProgramState.o ProgramState.cpp

ReturnStatement.o: ReturnStatement.cpp ReturnStatement.h \
		ProgramState.h \
		stackint.h \
		llistint.h \
		Statement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ReturnStatement.o ReturnStatement.cpp

stackint.o: stackint.cpp stackint.h \
		llistint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stackint.o stackint.cpp

SubStatement.o: SubStatement.cpp SubStatement.h \
		ProgramState.h \
		stackint.h \
		llistint.h \
		Statement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SubStatement.o SubStatement.cpp

moc_DebuggerWindow.o: moc_DebuggerWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DebuggerWindow.o moc_DebuggerWindow.cpp

moc_LoadWindow.o: moc_LoadWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LoadWindow.o moc_LoadWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

